"""Esquema inicial ERP (MySQL)

Revision ID: 001_initial
Revises:
Create Date: 2026-07-06

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(255), nullable=True),
    sa.Column('description', sa.String(255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(255), nullable=True),
    sa.Column('company', sa.String(255), nullable=True),
    sa.Column('ruc_ci', sa.String(255), nullable=True),
    sa.Column('phone', sa.String(255), nullable=True),
    sa.Column('email', sa.String(255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('client_type', sa.String(255), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruc_ci')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_table('company_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(255), nullable=True),
    sa.Column('logo', sa.String(255), nullable=True),
    sa.Column('company_icon', sa.String(255), nullable=True),
    sa.Column('primary_color', sa.String(255), nullable=True),
    sa.Column('secondary_color', sa.String(255), nullable=True),
    sa.Column('accent_color', sa.String(255), nullable=True),
    sa.Column('font_color', sa.String(255), nullable=True),
    sa.Column('quotation_validity_days', sa.Integer(), nullable=True),
    sa.Column('quotation_footer_text', sa.String(255), nullable=True),
    sa.Column('iva_default', sa.Integer(), nullable=True),
    sa.Column('guide_sender_name', sa.String(255), nullable=True),
    sa.Column('guide_sender_city', sa.String(255), nullable=True),
    sa.Column('guide_sender_region', sa.String(255), nullable=True),
    sa.Column('guide_sender_phone', sa.String(255), nullable=True),
    sa.Column('guide_sender_address', sa.String(255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measurement_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(255), nullable=True),
    sa.Column('abbreviation', sa.String(255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation')
    )
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product_colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product_themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product_thicknesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(255), nullable=True),
    sa.Column('name', sa.String(255), nullable=True),
    sa.Column('description', sa.String(255), nullable=True),
    sa.Column('category', sa.String(255), nullable=True),
    sa.Column('material', sa.String(255), nullable=True),
    sa.Column('color', sa.String(255), nullable=True),
    sa.Column('size', sa.String(255), nullable=True),
    sa.Column('thickness', sa.String(255), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('theme', sa.String(255), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('custom', sa.Boolean(), nullable=False),
    sa.Column('image', sa.String(255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(255), nullable=True),
    sa.Column('full_name', sa.String(255), nullable=True),
    sa.Column('password', sa.String(255), nullable=True),
    sa.Column('role', sa.String(255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('movement_type', sa.String(255), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('previous_stock', sa.Float(), nullable=True),
    sa.Column('new_stock', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('iva', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('shipping_cost', sa.Float(), nullable=True),
    sa.Column('status', sa.String(255), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('design_file', sa.String(255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=True),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.String(255), nullable=True),
    sa.Column('designer', sa.String(255), nullable=True),
    sa.Column('fabricator', sa.String(255), nullable=True),
    sa.Column('assigned_to', sa.String(255), nullable=True),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('observations', sa.String(255), nullable=True),
    sa.Column('notes', sa.String(255), nullable=True),
    sa.Column('design_file_name', sa.String(length=255), nullable=True),
    sa.Column('design_material', sa.String(length=50), nullable=True),
    sa.Column('design_size', sa.String(length=100), nullable=True),
    sa.Column('design_usb_reference', sa.String(length=100), nullable=True),
    sa.Column('design_notes', sa.Text(), nullable=True),
    sa.Column('design_copies', sa.Integer(), nullable=True),
    sa.Column('design_completed_at', sa.DateTime(), nullable=True),
    sa.Column('design_completed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['design_completed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_orders_quotation_id'), 'production_orders', ['quotation_id'], unique=True)
    op.create_table('quotation_designs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotation_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(255), nullable=True),
    sa.Column('measure', sa.String(255), nullable=True),
    sa.Column('theme', sa.String(255), nullable=True),
    sa.Column('color', sa.String(255), nullable=True),
    sa.Column('logo', sa.Boolean(), nullable=True),
    sa.Column('logo_type', sa.String(length=20), nullable=False),
    sa.Column('item_discount', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('product_image', sa.String(255), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_items_id'), 'quotation_items', ['id'], unique=False)
    op.create_table('quotation_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('transfer_receipt', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=True),
    sa.Column('guide_number', sa.String(255), nullable=True),
    sa.Column('customer_name', sa.String(255), nullable=True),
    sa.Column('customer_phone', sa.String(255), nullable=True),
    sa.Column('origin_city', sa.String(255), nullable=True),
    sa.Column('destination_city', sa.String(255), nullable=True),
    sa.Column('destination_address', sa.String(255), nullable=True),
    sa.Column('carrier', sa.String(255), nullable=True),
    sa.Column('boxes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(255), nullable=True),
    sa.Column('customer_id_number', sa.String(255), nullable=True),
    sa.Column('status', sa.String(255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('design_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_item_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quotation_item_id'], ['quotation_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quotation_item_id')
    )
    op.create_table('production_order_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_order_history_production_order_id'), 'production_order_history', ['production_order_id'], unique=False)
    op.create_table('production_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=True),
    sa.Column('quotation_item_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['quotation_item_id'], ['quotation_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quotation_id'),
    sa.UniqueConstraint('quotation_item_id')
    )
    op.create_table('design_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('design_tracking_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['design_tracking_id'], ['design_tracking.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('design_observations')
    op.drop_table('production_tracking')
    op.drop_index(op.f('ix_production_order_history_production_order_id'), table_name='production_order_history')
    op.drop_table('production_order_history')
    op.drop_table('design_tracking')
    op.drop_table('shipments')
    op.drop_table('quotation_payments')
    op.drop_index(op.f('ix_quotation_items_id'), table_name='quotation_items')
    op.drop_table('quotation_items')
    op.drop_table('quotation_designs')
    op.drop_index(op.f('ix_production_orders_quotation_id'), table_name='production_orders')
    op.drop_table('production_orders')
    op.drop_table('quotations')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('product_thicknesses')
    op.drop_table('product_themes')
    op.drop_table('product_materials')
    op.drop_table('product_colors')
    op.drop_table('product_categories')
    op.drop_table('measurement_units')
    op.drop_table('company_config')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
